name: CI

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_EC2_METADATA_DISABLED: true

jobs:
 deploy-website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install terraform 
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform
          terraform --version

      - name: terraform workflow
        run: |
          cd backEnd
          terraform init
          terraform fmt
          terraform validate
          terraform apply --auto-approve

      - name: aws workflow
        run: |
          cd frontEndJS
          aws s3 website s3://calebvarghese.com--index-document index.html --error-document index.html
          aws s3 sync . s3://calebvarghese.com/
          cd ../backEnd
          aws s3api put-bucket-policy --bucket calebvarghese.com --policy file://policy.json
          cd ..


